name: remote ssh command
on:
  push:
    branches:
      - main
      - master        
    paths:
      - 'typesBundle.json'
  pull_request:
    branches:
      - main
      - master        
    paths:
      - 'typesBundle.json'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: indexer.sh
